services:
    _defaults: { public: true }

    hbm.async_worker.messenger:
        class: HBM\AsyncWorkerBundle\Services\Messenger
        arguments: ['%hbm.async_worker%', '@hbm.async_worker.redis', '@logger']

    hbm.async_worker.runner:
        class: HBM\AsyncWorkerBundle\Command\RunnerCommand
        arguments: ['%hbm.async_worker%', '@hbm.async_worker.messenger', '@long_running.delegating_cleaner', '@logger', '@mailer', '@templating']
        tags:
            - { name: 'console.command' }
