services:
    _defaults:
        public: true
        autowire: false

    # SERVICES
    hbm.async_worker.console_logger:
        class: HBM\AsyncWorkerBundle\Services\ConsoleLogger
        arguments:
            $config: '%hbm.async_worker%'
            $logger: '@logger'

    hbm.async_worker.messenger:
        class: HBM\AsyncWorkerBundle\Services\Messenger
        arguments:
            $config: '%hbm.async_worker%'
            $redis: '@hbm.async_worker.alias.redis'
            $consoleLogger: '@hbm.async_worker.console_logger'

    hbm.async_worker.informer:
        class: HBM\AsyncWorkerBundle\Services\Informer
        arguments:
            $config: '%hbm.async_worker%'
            $mailer: '@mailer'
            $templating: '@hbm.async_worker.alias.templating'
            $consoleLogger: '@hbm.async_worker.console_logger'

    # COMMANDS
    HBM\AsyncWorkerBundle\Command\Execution\ListenCommand:
        arguments:
            $config: '%hbm.async_worker%'
            $messenger: '@hbm.async_worker.messenger'
            $informer: '@hbm.async_worker.informer'
            $consoleLogger: '@hbm.async_worker.console_logger'
            $cleaner: '@long_running.delegating_cleaner'
        tags:
            - { name: console.command }

    HBM\AsyncWorkerBundle\Command\Execution\SingleCommand:
        arguments:
            $config: '%hbm.async_worker%'
            $messenger: '@hbm.async_worker.messenger'
            $informer: '@hbm.async_worker.informer'
            $consoleLogger: '@hbm.async_worker.console_logger'
        tags:
            - { name: console.command }

    HBM\AsyncWorkerBundle\Command\InfoCommand:
        arguments:
            $messenger: '@hbm.async_worker.messenger'
        tags:
            - { name: console.command }

    HBM\AsyncWorkerBundle\Command\ResetCommand:
        arguments:
            $messenger: '@hbm.async_worker.messenger'
            $consoleLogger: '@hbm.async_worker.console_logger'
        tags:
            - { name: console.command }

    HBM\AsyncWorkerBundle\Command\ShutdownCommand:
        arguments:
            $messenger: '@hbm.async_worker.messenger'
            $consoleLogger: '@hbm.async_worker.console_logger'
        tags:
            - { name: console.command }

    HBM\AsyncWorkerBundle\Command\UpdateCommand:
        arguments:
            $messenger: '@hbm.async_worker.messenger'
            $consoleLogger: '@hbm.async_worker.console_logger'
        tags:
            - { name: console.command }
